---

- hosts: "all"
  become: true

  tasks:
    - name: "Install packages"
      apt:
        name: ['nginx', 'docker.io', 'python3-pip']
        state: "latest"
        update_cache: true

    - name: Install pip packages
      pip:
        name: [ 'docker-py' ]

    - name: Pull docker image
      shell: docker pull savoloon/django_test3

    - name: Remove old container
      docker_container:
        name: django_test3
        image: savoloon/django_test3
        state: absent

    - name: Create directories
      file: path={{ item }} state=directory mode=0700
      with_items:
        - "/var/docker/django_test4/data"

    - name: Create www directories
      file: path={{ item }} state=directory owner=www-data
      with_items:
        - "/var/www/django_test4/static"
        - "/var/log/www/django_test4"


    - name: Start container db
      docker_container:
        name: django-test4-db
        image: postgres:13.1
        volumes: "/var/docker/django_test4/data/:/var/lib/postgresql/data/"
        restart_policy: always
        state: started
        env:
          POSTGRES_PASSWORD: "{{ POSTGRES_PASSWORD }}"
          POSTGRES_USER: django_test4
          POSTGRES_NAME: django_test4

    - name: Start container
      docker_container:
        name: django-test4
        image: savoloon/django_test3
        restart_policy: always
        state: started
        links:
          - "django-test4-db:db"
        ports:
          - 127.0.0.1:8854:80
        volumes:
          - "/var/www/django_test4/static:/static"
        env:
          POSTGRESQL_PASS: "{{ POSTGRES_PASSWORD }}"

    - name: Install npm
      shell: docker exec -i django-test4 bash -c "npm install"

    - name: Collect static
      shell: docker exec -i django-test4 bash -c "python3 ./manage.py collectstatic --noinput"

    - name: Copy npm packegs
      shell: docker exec -i django-test4 bash -c "rm -rf static/node_modules; mv node_modules static/"

    - name: Restart container
      shell: docker restart django-test4

    - name: Set web static permissions
      file:
        path: /var/www/django_test4/static
        state: directory
        owner: www-data
        recurse: yes

    - name: Wait django-test4 start
      shell: sleep 2

    - name: Migrate db
      shell: docker exec -i django-test4 bash -c "python3 ./manage.py migrate"

    - name: Create nginx config
      template: src=nginx.jinja2 dest=/etc/nginx/sites-enabled/default
      register: nginx_conf

    - name: Restart nginx
      service: name=nginx state=reloaded
      when: nginx_conf.changed